#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


cp -r 0.org 0
cd utilities/chemkin1DSinCircleToFoam
wclean;wmake
cd ..;cd ..

# Get application name
application=`getApplication`
runApplication blockMesh
runApplication chemkin1DSinCircleToFoam
runApplication decomposePar -force
runParallel $(getApplication)
reconstructPar
paraFoam