#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

wclean;wmake
cd 2D_syngas_premixed
cp -r 0.org 0

# Get application name
application=`getApplication`
runApplication blockMesh
runApplication 1DFlameSin2Foam
paraFoam